### ISSUE TITLE
Ability to add jobs at run-time

### ISSUE THREAD

**Issue by dantswain** [c-rack/quantum-elixir#1]
Hi @c-rack, have you considered adding an API call to allow users to add jobs at runtime?

The reason I'm asking is I don't think specifying jobs through the config file will work with my production deployment model, where a sys.config file is generated from the mix config scripts.

I think it would be relatively easy to do this - just add an API function and a corresponding `handle_call`.  I would be glad to do this and make a pull request if it would help.

**Comment by c-rack** [comment]
Yes, I have already implemented that and later removed because I did not see a use case for that, see https://github.com/c-rack/quantum-elixir/commit/bf3891391bc3bd4a1914f87c91627694281004d0 and https://github.com/c-rack/quantum-elixir/commit/d8ba861e43c8b36beb86a604dfa6a2eecd1fda67.

Feel free to send a PR to re-add this functionality.

**Comment by c-rack** [comment]
Thanks! :+1:
