### ISSUE TITLE
Problem: inconsistent wording to start/stop jobs

### ISSUE THREAD

**Issue by c-rack** [c-rack/quantum-elixir#21]
Currently, we have `suspend_job` and `activate_job` to pause resp. resume a named job.

Let me propose to use another better word pair:

1. `activate` and `deactivate`
2. `suspend` and `resume`
3. `pause` and `resume`

I have sympathy for pair 3. Any comments?

**Comment by alPacino** [comment]
Yes, I agree that `suspend` is not quite correct word using it with `activate`. I like pair 1 because we indeed activate/deactivate scheduling for certain job. I mean that we don't pause the running job. So when you deactivate some job it would not be performed until activating it back or restarting the app. Concerning pause/resume for currently running jobs: I'm not sure if that may be implemented. Let's say we have job like this:
```
...
# Here comes some code to notify a user or whatever
...
transaction do
  insert_post(%Post{...})
  # Pause here somehow
  insert_comment(%Comment{...})
end
```

So we should save the current job's state and rollback the transaction. On resuming we need to ignore everything before transaction, start transaction again and perform with data from saved state. It's not so easy to implement.

**Comment by c-rack** [comment]
Agreed. I'll prepare a PR to change this to `activate` / `deactivate`.
