### ISSUE TITLE
Would this work out of the box on heroku?

### ISSUE THREAD

**Issue by tispratik** [c-rack/quantum-elixir#60]
Seems like quantum uses the same process as the one thats running the Phoenix web application.
In that case, i think we would not need another dyno or a scheduler service to schedule the crons?

**Comment by c-rack** [comment]
@tispratik I have not used heroku yet, so I can not answer your question reliably, but as quantum is just another application within the phoenix project (like cowboy, logger, httpoison, etc), I do not see any reason why this would need another dyno or scheduler. So yes, I think your assumption is correct.

Does this answer your question?

**Comment by tispratik** [comment]
Yes that does answer. But i was surprised by the discussion here https://groups.google.com/forum/#!msg/elixir-lang-talk/4gbcn709t3Y/EQk856vHfTQJ . Someone suggested that quantum cannot be used in heroku.

**Comment by c-rack** [comment]
Thanks for the link!

They say there is a problem on the free plan, where instances seem to be shut down.
So as long as you have a paid plan, quantum should work fine.

Can we close this issue as solved then?

**Comment by tispratik** [comment]
Sure thanks for looking into it Constantin!

**Comment by c-rack** [comment]
Thanks for asking!

**Comment by theoretick** [comment]
@tispratik @c-rack do yall think this warrants a note in the README for heroku free-tier or is it too edge-casey?

**Comment by tispratik** [comment]
Probably a note that Heroku free tier has a downtime of 6 hours a day, so
the cron may not run.

**Comment by c-rack** [comment]
With regard to #45, I would not include this into README right now. Please let me explain why.

If someone else asks the question a second time, we have an indication that there is maybe a need for a FAQ section that could include this question. Let us decide about it when this happens.

Until then, I think it is enough to have it documented in this issue, because we could easily refer to this issue if questions comes up again in IRC etc. and people can `+1` your suggestion.

Also, adding such a note is like adding another *dependency* that we have to maintain (i.e. we have to update this every time Heroku changes its free plan). And we should avoid dependencies if possible :-)

**Comment by theoretick** [comment]
Great points :+1: .  Let's see if this crops up again.

**Comment by tispratik** [comment]
I agree. Thanks.

**Comment by udfalkso** [comment]
What happens if I'm running with multiple dynos on Heroku?  Will my job get run multiple times?  Or does it behave as if there's only one application?  Thanks

**Comment by tonydaly** [comment]
@udfalkso did you get anywhere running this on Heroku with multiple dynos?

**Comment by seanwash** [comment]
@udfalkso I believe that your job would be run multiple times, yes. I'm currently using quantum on heroku and I notice that when I run `heroku run iex -S mix` that all of my scheduled tasks run there as well as on my main dyno at the same time.

**Comment by udfalkso** [comment]
No, I never attempted this.  Was just curious.  If I had this need today,  I'd probably go with gigalixir.com or some setup with proper elixir/erlang cluster support instead of Heroku.

**Comment by seanwash** [comment]
@tonydaly @udfalkso FYI there are some notes about this here: https://elixirforum.com/t/start-a-worker-on-heroku/11330
